import { TIME_PERIODS_MS } from '@shared/constants';

export const ANIMATION_CONFIG = {
	DURATION: {
		NORMAL: 0.6,
		SLOW: 1.0,
	},
	EASING: {
		EASE_OUT: [0.4, 0, 0.2, 1],
		EASE_PULSE: [0.4, 0, 0.6, 1],
	},
	EASING_NAMES: {
		EASE_OUT: 'easeOut',
		LINEAR: 'linear',
	},
} as const;

export enum AnimationDelays {
	STAGGER_EXTRA_SMALL = 0.03,
	STAGGER_SMALL = 0.05,
	STAGGER_NORMAL = 0.1,
	STAGGER_LARGE = 0.2,
	SEQUENCE_MEDIUM = 0.2,
	SEQUENCE_LARGE = 0.4,
	SEQUENCE_AFTER_HEADER = 0.7,
	SEQUENCE_STATS_BASE = 0.8,
	SINGLE_SUMMARY_HEADER_TAIL = 0.6,
	SINGLE_SUMMARY_STATS_CORRECT = 0.9,
	SINGLE_SUMMARY_STATS_TIME = 1.0,
	SINGLE_SUMMARY_ACTION_BUTTONS = 1.1,
	MULTIPLAYER_STANDINGS_ROW_BASE = 0.5,
}

export const SINGLE_SUMMARY_STAR_SEQUENCE_MS = {
	CONTAINER_DELAY_MS: AnimationDelays.SEQUENCE_AFTER_HEADER * 1000,
	BEFORE_FIRST_STAR_MS: TIME_PERIODS_MS.SECOND + TIME_PERIODS_MS.TWO_HUNDRED_MILLISECONDS,
	BETWEEN_STARS_MS: TIME_PERIODS_MS.SECOND,
} as const;

export const SPRING_CONFIGS = {
	GENTLE: { stiffness: 150, damping: 15 },
	BOUNCY: { stiffness: 200, damping: 15, mass: 1.5 },
	SMOOTH: { stiffness: 100, damping: 20 },
	ICON_SPRING: { stiffness: 200, damping: 15 },
} as const;

export const TRANSITION_DURATIONS = {
	FAST: 0.3,
	NORMAL: 0.4,
	SMOOTH: 0.5,
	SLOW: 0.6,
} as const;
