import { AVATAR_ALLOWED_MIME_TYPES, VALIDATION_COUNT } from '@shared/constants';

export const AVATAR_ID_CLEAR = VALIDATION_COUNT.AVATAR_ID.CLEAR;

export const ACCEPT_IMAGE = AVATAR_ALLOWED_MIME_TYPES.join(',');
