export enum LoadingMessages {
	LOADING_APP = 'loading:loadingApp',
	LOADING_BALANCE = 'loading:loadingBalance',
	LOADING_PROFILE = 'loading:loadingProfile',
	LOADING_QUESTION = 'loading:loadingQuestion',
	PROCESSING = 'loading:processing',
	SENDING = 'loading:sending',
	SIGNING_IN = 'loading:signingIn',
	CREATING_ACCOUNT = 'loading:creatingAccount',
	SAVING = 'loading:saving',
	CLEARING = 'loading:clearing',
	CONNECTING = 'loading:connecting',
	FETCHING_QUESTIONS = 'loading:fetchingQuestions',
	FETCHING_QUESTIONS_HINT = 'loading:fetchingQuestionsHint',
	VALIDATING_QUESTIONS = 'loading:validatingQuestions',
	INITIALIZING_SESSION = 'loading:initializingSession',
	READY = 'loading:ready',
	PREPARING_SUMMARY = 'loading:preparingSummary',
	AUTHENTICATING = 'loading:authenticating',
	CONNECTING_TO_SOCKET = 'loading:connectingToSocket',
	JOINING_ROOM = 'loading:joiningRoom',
	WAITING_FOR_GAME_STATE = 'loading:waitingForGameState',
	LOADING_MULTIPLAYER_QUESTIONS = 'loading:loadingMultiplayerQuestions',
	NO_QUESTIONS_AVAILABLE = 'loading:noQuestionsAvailable',
}
