export enum LoadingMessages {
	LOADING_APP = 'Loading the app...',
	LOADING_BALANCE = 'Loading balance...',
	LOADING_PROFILE = 'Loading profile...',
	LOADING_QUESTION = 'Loading question...',
	PROCESSING = 'Processing...',
	SENDING = 'Sending...',
	SIGNING_IN = 'Signing in...',
	CREATING_ACCOUNT = 'Creating account...',
	SAVING = 'Saving...',
	CLEARING = 'Clearing...',
	CONNECTING = 'Connecting to server...',
	FETCHING_QUESTIONS = 'Fetching questions from server...',
	FETCHING_QUESTIONS_HINT = 'This may take up to a minute when the service is busy.',
	VALIDATING_QUESTIONS = 'Validating questions...',
	INITIALIZING_SESSION = 'Initializing game session...',
	READY = 'Ready to start...',
	PREPARING_SUMMARY = 'Preparing your summary...',
	AUTHENTICATING = 'Authenticating...',
	CONNECTING_TO_SOCKET = 'Connecting to multiplayer server...',
	JOINING_ROOM = 'Joining room...',
	WAITING_FOR_GAME_STATE = 'Waiting for game state...',
	WAITING_FOR_OTHER_PLAYERS = 'Waiting for other players...',
	LOADING_MULTIPLAYER_QUESTIONS = 'Loading questions...',
	NO_QUESTIONS_AVAILABLE = 'No questions available',
}
