export enum SkeletonVariant {
	Icon = 'icon',
	IconLarge = 'iconLarge',
	IconNarrow = 'iconNarrow',
	Text = 'text',
	TextDescription = 'textDescription',
	TextLine = 'textLine',
	TextWithSmallWidth = 'textWithSmallWidth',
	TextSmall = 'textSmall',
	TextSmallLine = 'textSmallLine',
	TextLarge = 'textLarge',
	TextLargeNarrow = 'textLargeNarrow',
	Badge = 'badge',
	Card = 'card',
	Row = 'row',
	TableRow = 'tableRow',
	Chart = 'chart',
	ChartSmall = 'chartSmall',
	ChartLarge = 'chartLarge',
	Label = 'label',
	Input = 'input',
	InputMedium = 'inputMedium',
	InputSmall = 'inputSmall',
	InputFull = 'inputFull',
	BlockSm = 'blockSm',
	BlockTall = 'blockTall',
	BlockLarge = 'blockLarge',
	BlockXl = 'blockXl',
}

export const SKELETON_PLACEHOLDER_COUNTS = {
	SMALL: 2,
	MEDIUM: 3,
	CARDS: 4,
	LIST: 5,
} as const;
