CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  score INT DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  avatar VARCHAR(255),
  isActive BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS trivia_history (
  id VARCHAR(36) PRIMARY KEY,
  topic VARCHAR(255) NOT NULL,
  difficulty VARCHAR(50) NOT NULL,
  question TEXT NOT NULL,
  answers JSON NOT NULL,
  correctAnswerIndex INT NOT NULL,
  userId VARCHAR(36),
  isCorrect BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id)
); 