import { TIME_PERIODS_MS } from '../core/time.constants';

export const HTTP_CLIENT_CONFIG = {
	TIMEOUT: TIME_PERIODS_MS.THIRTY_SECONDS,
	RETRY_ATTEMPTS: 3,
	RETRY_ATTEMPTS_RATE_LIMIT: 5,
	RETRY_DELAY: TIME_PERIODS_MS.SECOND,
	RETRY_DELAY_RATE_LIMIT: TIME_PERIODS_MS.FIVE_SECONDS,
	DEFAULT_HEADERS: {
		'Content-Type': 'application/json',
		Accept: 'application/json',
	},
} as const;

export const HTTP_TIMEOUTS = {
	QUESTION_GENERATION: 55 * TIME_PERIODS_MS.SECOND,
	AI_PROVIDER: TIME_PERIODS_MS.THIRTY_SECONDS,
	UPLOAD: TIME_PERIODS_MS.MINUTE,
	TRIVIA_CLIENT: TIME_PERIODS_MS.TWO_MINUTES,
} as const;

export const HTTP_STATUS_CODES = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_SERVER_ERROR: 500,
	BAD_GATEWAY: 502,
	SERVICE_UNAVAILABLE: 503,
	GATEWAY_TIMEOUT: 504,
	SERVER_ERROR_MIN: 500,
	SERVER_ERROR_MAX: 599,
} as const;

export enum HttpMethod {
	GET = 'GET',
	POST = 'POST',
	PUT = 'PUT',
	PATCH = 'PATCH',
	DELETE = 'DELETE',
	OPTIONS = 'OPTIONS',
}
