export const ENV_VAR_NAMES = {
	API_BASE_URL: 'VITE_API_BASE_URL', // Unified name for API URL
	CLIENT_URL: 'VITE_CLIENT_URL',
	SERVER_URL: 'VITE_SERVER_URL',
	DATABASE_HOST: 'DATABASE_HOST',
	DATABASE_PORT: 'DATABASE_PORT',
	REDIS_HOST: 'REDIS_HOST',
	REDIS_PORT: 'REDIS_PORT',
	CORS_ORIGIN: 'CORS_ORIGIN',
} as const;
