export enum CreditTransactionType {
	DAILY_RESET = 'DAILY_RESET',
	PURCHASE = 'PURCHASE',
	GAME_USAGE = 'GAME_USAGE',
	ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
	REFUND = 'REFUND',
}

export enum CreditSource {
	FREE_DAILY = 'FREE_DAILY',
	PURCHASED = 'PURCHASED',
	BONUS = 'BONUS',
	REFUND = 'REFUND',
}
