export const API_ENDPOINTS = {
	AUTH: {
		BASE: '/auth',
		ME: '/auth/me',
		LOGIN: '/auth/login',
		REGISTER: '/auth/register',
		LOGOUT: '/auth/logout',
		REFRESH: '/auth/refresh',
		GOOGLE: '/auth/google',
		GOOGLE_CALLBACK: '/auth/google/callback',
		ADMIN_USERS: '/auth/admin/users',
	},
	USER: {
		BASE: '/users',
		PROFILE: '/users/profile',
		AVATAR: '/users/avatar',
		SEARCH: '/users/search',
		ACCOUNT: '/users/account',
		CHANGE_PASSWORD: '/users/change-password',
		PREFERENCES: '/users/preferences',
		PROFILE_FIELD: '/users/profile/:field',
		PREFERENCES_FIELD: '/users/preferences/:preference',
		GET_BY_ID: '/users/:id',
		BY_ID: '/users/:id',
		BY_USER_ID: '/users/:userId',
		UPDATE_CREDITS: '/users/credits/:userId',
		CREDITS_BY_USER_ID: '/users/credits/:userId',
		UPDATE_STATUS: '/users/:userId/status',
		ADMIN: {
			ALL: '/users/admin/all',
			STATUS_BY_USER_ID: '/users/admin/:userId/status',
		},
	},
	GAME_HISTORY: {
		DELETE: (id: string) => `/game-history/${id}`,
		CLEAR: '/game-history',
		BY_ID: (id: string) => `/game-history/${id}`,
	},
	PAYMENT: {
		BASE: '/payment',
		HISTORY: '/payment/history',
		CREATE: '/payment/create',
		WEBHOOK_PAYPAL: '/payment/webhooks/paypal',
		PURCHASE_CREDITS: '/payment/purchase-credits',
	},
	CREDITS: {
		BASE: '/credits',
		BALANCE: '/credits/balance',
		HISTORY: '/credits/history',
		PACKAGES: '/credits/packages',
		CAN_PLAY: '/credits/can-play',
		DEDUCT: '/credits/deduct',
	},
	GAME: {
		BASE: '/game',
		TRIVIA_BY_ID: '/game/trivia/:id',
		ANSWER: '/game/answer',
		TRIVIA: '/game/trivia',
		HISTORY: '/game/history',
		HISTORY_BY_ID: '/game/history/:gameId',
		VALIDATE_CUSTOM: '/game/validate-custom',
		SESSION_START: '/game/session/start',
		SESSION_ANSWER: '/game/session/answer',
		SESSION_FINALIZE: '/game/session/finalize',
		VALIDATE_SESSION: '/game/validate-session/:gameId',
		BY_ID: '/game/:id',
		ADMIN: {
			STATISTICS: '/admin/statistics',
			HISTORY_CLEAR_ALL: '/admin/history/clear-all',
			TRIVIA: '/admin/trivia',
			TRIVIA_CLEAR_ALL: '/admin/trivia/clear-all',
		},
	},
	MULTIPLAYER: {
		BASE: '/multiplayer',
		ROOMS: '/multiplayer/rooms',
		ROOMS_JOIN: '/multiplayer/rooms/join',
		ROOMS_LEAVE: '/multiplayer/rooms/leave',
		ROOMS_START: '/multiplayer/rooms/start',
		ROOMS_ANSWER: '/multiplayer/rooms/answer',
		ROOMS_BY_ID: '/multiplayer/rooms/:roomId',
		ROOMS_STATE: '/multiplayer/rooms/:roomId/state',
	},
	ANALYTICS: {
		BASE: '/analytics',
		USER: '/analytics/user',
		USER_STATS: '/analytics/user/statistics/:userId',
		USER_PERFORMANCE: '/analytics/user/performance/:userId',
		USER_PROGRESS: '/analytics/user/progress/:userId',
		USER_ACTIVITY: '/analytics/user/activity/:userId',
		USER_INSIGHTS: '/analytics/user/insights/:userId',
		USER_RECOMMENDATIONS: '/analytics/user/recommendations/:userId',
		USER_ACHIEVEMENTS: '/analytics/user/achievements/:userId',
		USER_TRENDS: '/analytics/user/trends/:userId',
		USER_COMPARISON: '/analytics/user/comparison/:userId',
		USER_SUMMARY: '/analytics/user/summary/:userId',
		TOPICS_POPULAR: '/analytics/global/topics/popular',
		DIFFICULTY_GLOBAL: '/analytics/global/difficulty',
		TRACK: '/analytics/track',
		GLOBAL_STATS: '/analytics/global/stats',
		GLOBAL_TRENDS: '/analytics/global/trends',
		BUSINESS_METRICS: '/analytics/business/metrics',
		SYSTEM_PERFORMANCE: '/analytics/system/performance',
		SYSTEM_SECURITY: '/analytics/system/security',
		SYSTEM_RECOMMENDATIONS: '/analytics/system/recommendations',
		SYSTEM_INSIGHTS: '/analytics/system/insights',
		ADMIN_STATS_CLEAR_ALL: '/admin/stats/clear-all',
		LEADERBOARD: {
			BASE: '/analytics/leaderboard',
			STATS: '/analytics/leaderboard/stats',
			GLOBAL: '/analytics/leaderboard/global',
			PERIOD: '/analytics/leaderboard/period/:period',
			ADMIN_CLEAR_ALL: '/analytics/leaderboard/admin/clear-all',
		},
	},
	AI_PROVIDERS: {
		BASE: '/ai-providers',
		STATS: '/ai-providers/stats',
		HEALTH: '/ai-providers/health',
	},
} as const;

export const COOKIE_NAMES = {
	AUTH_TOKEN: 'auth_token',
	REFRESH_TOKEN: 'refresh_token',
	USER_PREFERENCES: 'user_preferences',
} as const;

export const API_VERSION = 'v1';

export const PAGINATION_DEFAULTS = {
	DEFAULT_PAGE: 1,
	DEFAULT_LIMIT: 10,
	MAX_LIMIT: 100,
} as const;

export const RATE_LIMIT_DEFAULTS = {
	WINDOW_MS: 60000,
	MAX_REQUESTS: 200,
	MAX_REQUESTS_PER_WINDOW: 200,
	BURST_LIMIT: 50,
	BURST_WINDOW_MS: 10000,
	MESSAGE: 'Too many requests, please try again later',
	BURST_MESSAGE: 'Rate limit exceeded, please slow down',
} as const;

export const QUERY_PARAMS = {
	LIMIT: 'limit',
	OFFSET: 'offset',
	PERIOD: 'period',
} as const;
