import { TIME_PERIODS_MS } from './time.constants';

export const API_ENDPOINTS = {
	AUTH: {
		BASE: '/auth',
		ME: '/auth/me',
		LOGIN: '/auth/login',
		REGISTER: '/auth/register',
		LOGOUT: '/auth/logout',
		REFRESH: '/auth/refresh',
		LEGAL_ACCEPTANCE: '/auth/legal-acceptance',
		GOOGLE: '/auth/google',
		GOOGLE_CALLBACK: '/auth/google/callback',
	},
	USER: {
		BASE: '/users',
		PROFILE: '/users/profile',
		AVATAR: '/users/avatar',
		AVATAR_UPLOAD: '/users/avatar/upload',
		AVATAR_IMAGE: '/users/:userId/avatar',
		SEARCH: '/users/search',
		CHANGE_PASSWORD: '/users/change-password',
		PREFERENCES: '/users/preferences',
		ADMIN: {
			ALL: '/users/admin/all',
			STATUS_BY_USER_ID: '/users/admin/:userId/status',
		},
	},
	PAYMENT: {
		BASE: '/payment',
		HISTORY: '/payment/history',
		PURCHASE_CREDITS: '/payment/purchase-credits',
	},
	CREDITS: {
		BASE: '/credits',
		BALANCE: '/credits/balance',
		PACKAGES: '/credits/packages',
		DEDUCT: '/credits/deduct',
	},
	GAME: {
		BASE: '/game',
		TRIVIA: '/game/trivia',
		HISTORY: '/game/history',
		HISTORY_BY_ID: '/game/history/:gameId',
		VALIDATE_TEXT: '/game/validate-text',
		VALIDATE_TRIVIA_TOPIC: '/game/validate-trivia-topic',
		SESSION_START: '/game/session/start',
		SESSION_ANSWER: '/game/session/answer',
		SESSION_FINALIZE: '/game/session/finalize',
		SURPRISE_PICK: '/game/surprise-pick',
		VALIDATE_SESSION: '/game/validate-session/:gameId',
	},
	MULTIPLAYER: {
		BASE: '/multiplayer',
		ROOMS: '/multiplayer/rooms',
		ROOMS_PUBLIC_WAITING: '/multiplayer/rooms/public-waiting',
		ROOMS_JOIN: '/multiplayer/rooms/join',
		ROOMS_LEAVE: '/multiplayer/rooms/leave',
		ROOMS_START: '/multiplayer/rooms/start',
		ROOMS_ANSWER: '/multiplayer/rooms/answer',
		ROOMS_BY_ID: '/multiplayer/rooms/:roomId',
		ROOMS_STATE: '/multiplayer/rooms/:roomId/state',
	},
	ANALYTICS: {
		BASE: '/analytics',
		USER: '/analytics/user',
		USER_STATS: '/analytics/user/statistics/:userId',
		USER_PERFORMANCE: '/analytics/user/performance/:userId',
		USER_INSIGHTS: '/analytics/user/insights/:userId',
		USER_RECOMMENDATIONS: '/analytics/user/recommendations/:userId',
		USER_COMPARISON: '/analytics/user/comparison/:userId',
		USER_SUMMARY: '/analytics/user/summary/:userId',
		TOPICS_POPULAR: '/analytics/global/topics/popular',
		DIFFICULTY_GLOBAL: '/analytics/global/difficulty',
		TRACK: '/analytics/track',
		GLOBAL_STATS: '/analytics/global/stats',
		GLOBAL_TRENDS: '/analytics/global/trends',
		BUSINESS_METRICS: '/analytics/business/metrics',
		SYSTEM_PERFORMANCE: '/analytics/system/performance',
		SYSTEM_SECURITY: '/analytics/system/security',
		SYSTEM_RECOMMENDATIONS: '/analytics/system/recommendations',
		SYSTEM_INSIGHTS: '/analytics/system/insights',
		LEADERBOARD: {
			STATS: '/analytics/leaderboard/stats',
			GLOBAL: '/analytics/leaderboard/global',
			PERIOD: '/analytics/leaderboard/period/:period',
			ADMIN_CLEAR_ALL: '/analytics/leaderboard/admin/clear-all',
		},
	},
	ADMIN: {
		BASE: '/admin',
		PRICING: '/admin/pricing',
		STATISTICS: '/admin/statistics',
		TRIVIA: '/admin/trivia',
	},
	MAINTENANCE: {
		BASE: '/admin/maintenance',
		STATS_CONSISTENCY_CHECK_ALL: '/admin/maintenance/stats/consistency-check/all',
		STATS_CONSISTENCY: '/admin/maintenance/stats/consistency/:userId',
		STATS_FIX_CONSISTENCY: '/admin/maintenance/stats/fix-consistency/:userId',
		DATA_GAME_HISTORY_CLEAR_ALL: '/admin/maintenance/data/game-history/clear-all',
		DATA_TRIVIA_CLEAR_ALL: '/admin/maintenance/data/trivia/clear-all',
		DATA_USER_STATS_CLEAR_ALL: '/admin/maintenance/data/user-stats/clear-all',
	},
	AI_PROVIDERS: {
		BASE: '/ai-providers',
		STATS: '/ai-providers/stats',
		HEALTH: '/ai-providers/health',
	},
} as const;

export const VITE_API_BUNDLE_USE_ORIGIN_PREFIX = 'USE_ORIGIN_API_PREFIX';

export const RATE_LIMIT_DEFAULTS = {
	WINDOW_MS: TIME_PERIODS_MS.MINUTE,
	MAX_REQUESTS: 200,
	MAX_REQUESTS_PER_WINDOW: 200,
	BURST_LIMIT: 50,
	BURST_WINDOW_MS: TIME_PERIODS_MS.TEN_SECONDS,
	MESSAGE: 'Too many requests, please try again later',
	BURST_MESSAGE: 'Rate limit exceeded, please slow down',
} as const;

export const QUERY_PARAMS = {
	LIMIT: 'limit',
	OFFSET: 'offset',
	PERIOD: 'period',
} as const;
