import {
  CircleDot as EasyIcon,
  Circle as MediumIcon,
  CircleOff as HardIcon,
  Palette as CustomIcon,
  History as HistoryIcon,
  AlertTriangle as ErrorIcon,
  Trophy as TrophyIcon,
  Star as StarIcon,
  User as UserIcon,
  Home as HomeIcon,
  X as CloseIcon,
  Check as CheckIcon,
  ChevronRight as NextIcon,
  ChevronLeft as PrevIcon,
  Info as InfoIcon,
  Settings as SettingsIcon,
  Lightbulb as TipIcon,
  Award as AchievementIcon,
  BarChart as StatsIcon,
  Clock as TimerIcon,
  Medal as MedalIcon,
  Flag as FlagIcon,
  ThumbsUp as LikeIcon,
  BookOpen as BookIcon,
  Zap as PowerIcon,
  PieChart as ChartIcon,
} from 'lucide-react';

export * from './achievements';

export {
  EasyIcon,
  MediumIcon,
  HardIcon,
  CustomIcon,
  HistoryIcon,
  ErrorIcon,
  TrophyIcon,
  StarIcon,
  UserIcon,
  HomeIcon,
  CloseIcon,
  CheckIcon,
  NextIcon,
  PrevIcon,
  InfoIcon,
  SettingsIcon,
  TipIcon,
  AchievementIcon,
  StatsIcon,
  TimerIcon,
  MedalIcon,
  FlagIcon,
  LikeIcon,
  BookIcon,
  PowerIcon,
  ChartIcon,
};