export const PUBLIC_ENDPOINTS = [
	'/analytics/leaderboard/global',
	'/analytics/leaderboard/period',
	'/analytics/leaderboard/stats',
	'/api/health',
	'/api/health/liveness',
	'/api/health/readiness',
	'/status',
	'/auth/login',
	'/auth/register',
	'/auth/refresh',
	'/auth/google',
	'/auth/google/callback',
	'/payment/webhooks/paypal',
] as const;
